Parameters:
  DbMasterUsername:
    Description: Enter master dbUsername
    Type: String
  DbMasterPassword:
    Description: Enter master db password
    Type: String
  InstanceTypeSize:
    Description: Select instance size
    Type: String
    Default: SMALL
    AllowedValues:
     - SMALL
     - MEDIUM
     - LARGE

Mappings:
  RegionMap:
    ca-central-1:
      AMZNLINUX: ami-0f75c2980c6a5851d
    us-east-1:
      AMZNLINUX: ami-09d95fab7fff3776c
  InstanceSize:
    SMALL:
      'EC2': 't2.micro'
      'DB': 'db.t2.micro'
    MEDIUM:
      'EC2': 't2.small'
      'DB': 'db.t2.small'
    LARGE:
      'EC2': 't2.medium'
      'DB': 'db.t2.medium'

Resources:
  DB:
    Type: 'AWS::RDS::DBInstance'
    Properties:
      DBInstanceClass: !FindInMap [InstanceSize, !Ref InstanceTypeSize, DB]
      DBName: wordpress
      Engine: MySQL
      MasterUsername: !Ref DbMasterUsername
      MasterUserPassword: !Ref DbMasterPassword
      AllocatedStorage: 5
      StorageType: gp2
  EC2:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: !FindInMap [RegionMap, !Ref 'AWS::Region', AMZNLINUX]
      InstanceType: !FindInMap [InstanceSize, !Ref InstanceTypeSize, EC2]
  S3:
    Type: 'AWS::S3::Bucket'