Parameters:
  DbName:
    Description: Enter db name
    Type: String
  DatabaseUser:
    Type: String
    Default: wordpress
  DatabasePassword:
    Description: Enter master db password
    Type: String
    NoEcho: True
  InstanceTypeSize:
    Description: Select instance size
    Type: String
    Default: SMALL
    AllowedValues:
     - SMALL
     - MEDIUM
     - LARGE
  KeyPairForEC2:
    Description: Existing KeyPair name
    Type: 'AWS::EC2::KeyPair::KeyName'

Mappings:
  RegionMap:
    ca-central-1:
      AMZNLINUX: ami-0f75c2980c6a5851d
    us-east-1:
      AMZNLINUX: ami-09d95fab7fff3776c
  InstanceSize:
    SMALL:
      'EC2': 't2.micro'
      'DB': 'db.t2.micro'
    MEDIUM:
      'EC2': 't2.small'
      'DB': 'db.t2.small'
    LARGE:
      'EC2': 't2.medium'
      'DB': 'db.t2.medium'

Resources:
  DB:
    Type: 'AWS::RDS::DBInstance'
    Properties:
      DBInstanceClass: !FindInMap [InstanceSize, !Ref InstanceTypeSize, DB]
      DBName: !Ref DbName
      Engine: MySQL
      MasterUsername: !Ref DatabaseUser
      MasterUserPassword: !Ref DatabasePassword
      AllocatedStorage: 5
      StorageType: gp2
  EC2:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: !FindInMap [RegionMap, !Ref 'AWS::Region', AMZNLINUX]
      InstanceType: !FindInMap [InstanceSize, !Ref InstanceTypeSize, EC2]
      KeyName: !Ref KeyPairForEC2
      UserData:
        "Fn::Base64":
          !Sub |
            #!/bin/bash
            yum install httpd php mysql php-mysql -y
            yum update -y
            chkconfig httpd on
            service httpd start
            cd /var/www/html
            wget https://wordpress.org/wordpress-5.1.1.tar.gz
            tar -xzf wordpress-5.1.1.tar.gz
            rm wordpress-5.1.1.tar.gz
            cp wp-config-sample.php wp-config.php
            sed -i 's/database_name_here/${DbName}/g' wp-config.php
            sed -i 's/localhost/${DB.Endpoint.Address}/g' wp-config.php
            sed -i 's/username_here/${DatabaseUser}/g' wp-config.php
            sed -i 's/password_here/${DatabasePassword}/g' wp-config.php
  S3:
    Type: 'AWS::S3::Bucket'